# Generated by Django 2.0.1 on 2020-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicalquantmgnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=500)),
                ('tablename', models.CharField(max_length=500)),
                ('components', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('soldtablets', models.IntegerField()),
                ('availablestock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medmedicalshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabletname', models.CharField(max_length=100)),
                ('brandname', models.CharField(max_length=100)),
                ('components', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medstoringsupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabletname', models.CharField(max_length=100)),
                ('brandname', models.CharField(max_length=100)),
                ('components', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('customer', models.CharField(max_length=20)),
                ('docfile', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Supquantmanagmnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=500)),
                ('tablename', models.CharField(max_length=500)),
                ('components', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('soldtablets', models.IntegerField()),
                ('availablestock', models.IntegerField()),
            ],
        ),
    ]
